### ISSUE TITLE
[6차 스프린트 - User, Review] 리팩터링

### ISSUE THREAD

**Issue by na-yk** [Team-Blitz-Steady/steady-server#174]
### 🔨 Describe

- 피드백을 받은 내용중 규모가 작은 사항들에 대해 전반적인 리팩터링을 진행하려고 합니다.

### ✅ Tasks

- [ ] 리뷰 생성 기능에서 리뷰 생성과 사용자 카드 생성을 한 트랜잭션에서 처리하기 위해 `createReview`와 `createUserCards` 두 메서드를 병합
- [ ] 한 줄로 짧게 끝나고 재사용하는 일이 적은 private 메서드는 불필요하다고 판단하여 제거
- [ ] 테스트 코드 불필요한 검증 제거
