### ISSUE TITLE
[2차 스프린트 - User] OAuth 컨트롤러 테스트 및 문서화

### ISSUE THREAD

**Issue by na-yk** [Team-Blitz-Steady/steady-server#68]
### 📄 Describe

Auth 도메인 Controller 테스트 작성 및 문서화

### ✅ Tasks

- [X] 로그인 페이지 요청 기능 Controller 테스트 추가
- [x] 최초 로그인 사용자의 로그인 기능 Controller 테스트 추가
- [x] 기존 회원의 로그인 기능 Controller 테스트 추가
